spring.application.name=observability-lab
server.port=8080
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%X{correlationId:-no-correlation-id}] %logger{36} - %msg%n
server.error.include-message=never