spring.application.name=read-api-lab
spring.datasource.url=jdbc:h2:mem:readapidb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
server.port=8080
